(()=>{"use strict";
const S={audio:null,button:null,token:null},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],cache=new Map();
const norm=s=>(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function stop(){if(S.audio){S.audio.pause();S.audio.currentTime=0}if(S.button){S.button.classList.remove("is-playing");S.button.textContent="Play"}S.audio=null;S.button=null}
async function spotifyFind(title,artist){if(!S.token)return null;try{const q=encodeURIComponent("track:"+title+" artist:"+artist),r=await fetch("https://api.spotify.com/v1/search?q="+q+"&type=track&limit=5",{headers:{Authorization:"Bearer "+S.token}});if(!r.ok)return null;const items=(await r.json()).tracks?.items||[],hit=items.find(x=>norm(x.name).includes(norm(title)))||items[0];return hit?{preview:hit.preview_url,url:hit.external_urls?.spotify}:null}catch{return null}}
async function appleFind(title,artist){try{const r=await fetch("https://itunes.apple.com/search?term="+encodeURIComponent(title+" "+artist)+"&entity=song&limit=12&country=us");if(!r.ok)return null;const items=(await r.json()).results||[],hit=items.find(x=>norm(x.trackName).includes(norm(title))&&norm(x.artistName).includes(norm(artist)))||items.find(x=>norm(x.trackName).includes(norm(title)));return hit?{preview:hit.previewUrl,url:hit.trackViewUrl}:null}catch{return null}}
async function resolve(title,artist){const k=norm(artist+"|"+title);if(cache.has(k))return cache.get(k);const x=await spotifyFind(title,artist)||await appleFind(title,artist)||{};cache.set(k,x);return x}
function unavailable(b,url){b.classList.remove("is-loading","is-playing");b.textContent="Extrait indisponible";b.disabled=true;if(url&&!b.parentElement.querySelector(".audio-platform-link")){const a=document.createElement("a");a.className="audio-platform-link";a.href=url;a.target="_blank";a.rel="noopener";a.textContent="Spotify ↗";b.after(a)}}
async function play(b,title,artist,fallback){if(S.button===b&&S.audio&&!S.audio.paused){S.audio.pause();b.classList.remove("is-playing");b.textContent="Play";return}stop();b.classList.add("is-loading");b.textContent="Chargement…";const x=await resolve(title,artist);b.classList.remove("is-loading");if(!x.preview){unavailable(b,x.url||fallback);return}const a=new Audio(x.preview);a.preload="auto";S.audio=a;S.button=b;b.textContent="Pause";b.classList.add("is-playing");a.addEventListener("ended",stop,{once:true});a.addEventListener("error",()=>unavailable(b,x.url||fallback),{once:true});try{await a.play()}catch{unavailable(b,x.url||fallback)}}
function info(b){const card=b.closest("article,li"),key=b.dataset.listen;let title=b.dataset.audioTitle||card?.querySelector("h3,strong,li>span")?.textContent?.trim()||"",artist=b.dataset.audioArtist||card?.querySelector("p")?.textContent?.split("·")[0]?.trim()||$(".artist-modal .profile-hero h2")?.textContent?.trim()||"",fallback="";if(key&&typeof ARTISTS!=="undefined"){const [id,...rest]=key.split("|"),a=ARTISTS.find(x=>x.id===id);title=rest.join("|")||title;artist=a?.name||artist;fallback=a?.source||""}return{title,artist,fallback}}
function activate(root=document){$$('button[aria-label="Extrait indisponible"]',root).forEach(b=>{const li=b.closest("li");b.disabled=false;b.classList.add("audio-trigger");b.dataset.audioTitle=li?.querySelector("span")?.textContent?.trim()||"";b.dataset.audioArtist=$(".artist-modal .profile-hero h2")?.textContent?.trim()||"";b.textContent="Play"});$$(".playlist-card button[disabled],.playlist article button[disabled]",root).forEach(b=>{const a=b.closest("article");b.disabled=false;b.classList.add("audio-trigger");b.dataset.audioTitle=a?.querySelector("h3")?.textContent?.trim()||"";b.dataset.audioArtist=a?.querySelector("p")?.textContent?.split("·")[0]?.trim()||"";b.textContent="Play"});$$(".top-tracks-view article",root).forEach(a=>{if(a.querySelector(".audio-trigger"))return;const b=document.createElement("button");b.type="button";b.className="audio-trigger";b.textContent="Play";b.dataset.audioTitle=a.querySelector("h3")?.textContent?.trim()||"";b.dataset.audioArtist=a.querySelector("p")?.textContent?.trim()||"";a.append(b)})}
document.addEventListener("click",e=>{const b=e.target.closest(".audio-trigger,.listen-trigger");if(!b)return;e.preventDefault();e.stopImmediatePropagation();const d=info(b);play(b,d.title,d.artist,d.fallback)},{capture:true});
new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>n.nodeType===1&&activate(n)))).observe(document.body,{childList:true,subtree:true});activate();
async function cfg(){try{const r=await fetch("/.netlify/functions/spotify-config",{cache:"no-store"});return r.ok?await r.json():{}}catch{return{}}}
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");async function challenge(v){return b64(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)))}function verifier(){const a=new Uint8Array(64);crypto.getRandomValues(a);return b64(a)}
async function connect(){const c=await cfg();if(!c.clientId){alert("Spotify attend SPOTIFY_CLIENT_ID dans Netlify.");return}const v=verifier(),redirect=c.redirectUri||location.origin+location.pathname;sessionStorage.setItem("dunder_spotify_verifier",v);sessionStorage.setItem("dunder_spotify_redirect",redirect);location.href="https://accounts.spotify.com/authorize?"+new URLSearchParams({client_id:c.clientId,response_type:"code",redirect_uri:redirect,code_challenge_method:"S256",code_challenge:await challenge(v),scope:"user-read-private user-read-email"})}
async function callback(){const u=new URL(location.href),code=u.searchParams.get("code");if(!code)return;const c=await cfg(),v=sessionStorage.getItem("dunder_spotify_verifier"),redirect=sessionStorage.getItem("dunder_spotify_redirect")||c.redirectUri||location.origin+location.pathname;if(!c.clientId||!v)return;const r=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId,grant_type:"authorization_code",code,redirect_uri:redirect,code_verifier:v})});if(!r.ok){alert("Connexion Spotify impossible.");return}const t=await r.json();localStorage.setItem("dunder_spotify_session",JSON.stringify({access:t.access_token,expires:Date.now()+t.expires_in*1000}));history.replaceState({},document.title,redirect)}
async function restore(){try{const s=JSON.parse(localStorage.getItem("dunder_spotify_session")||"null");if(!s||s.expires<=Date.now())return;S.token=s.access;const r=await fetch("https://api.spotify.com/v1/me",{headers:{Authorization:"Bearer "+s.access}});if(!r.ok)return;const p=await r.json(),btn=$("#spotify-connect");if(!btn)return;const d=document.createElement("div");d.className="spotify-session";const img=p.images?.[0]?.url;d.innerHTML=(img?'<img src="'+img+'" alt="">':"")+'<span><strong>'+String(p.display_name||"Compte Spotify").replace(/[<>&]/g,"")+'</strong><small>Spotify connecté</small></span><button type="button" id="spotify-disconnect">Déconnexion</button>';btn.replaceWith(d);$("#spotify-disconnect").onclick=()=>{stop();localStorage.removeItem("dunder_spotify_session");location.reload()}}catch{}}
$("#spotify-connect")?.addEventListener("click",connect);callback().then(restore);
})();
