const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const shuffle=items=>{const copy=[...items];for(let i=copy.length-1;i>0;i--){const random=new Uint32Array(1);crypto.getRandomValues(random);const j=random[0]%(i+1);[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
const focusIds=['okiz','erton','enzalevrai'];
const editorialOrder=items=>[...shuffle(items.filter(x=>focusIds.includes(x.id||x.artistId))),...shuffle(items.filter(x=>!focusIds.includes(x.id||x.artistId)))];
const themeDialog=document.querySelector('.theme-dialog'),themeLaunchers=[...document.querySelectorAll('.theme-launcher')],themeCards=[...document.querySelectorAll('[data-theme-choice]')],themeLabels=[...document.querySelectorAll('[data-theme-label]')],themeLogos=[...document.querySelectorAll('[data-theme-logo]')],savedTheme=localStorage.getItem('dunder-theme')||'black';function updateThemeControl(theme){themeLabels.forEach(label=>label.textContent=theme==='green'?'MBOA':theme.toUpperCase());themeCards.forEach(card=>{const active=card.dataset.themeChoice===theme;card.classList.toggle('active',active);card.setAttribute('aria-pressed',String(active));card.querySelector('[data-active-label]').textContent=active?'ACTIVE':'CHOISIR'})}function applyTheme(theme){document.documentElement.dataset.theme=theme;themeLogos.forEach(logo=>{logo.src=theme==='green'?'d-under-logo.png':'d-under-logo-transparent.png'});updateThemeControl(theme);localStorage.setItem('dunder-theme',theme)}function setTheme(theme,animate=true){if(!animate){applyTheme(theme);return}document.documentElement.classList.add('theme-shifting');const change=()=>applyTheme(theme);if(document.startViewTransition){document.startViewTransition(change)}else{change()}setTimeout(()=>document.documentElement.classList.remove('theme-shifting'),720)}applyTheme(savedTheme);themeLaunchers.forEach(button=>button.addEventListener('click',()=>themeDialog.showModal()));document.querySelector('.theme-dialog-close').addEventListener('click',()=>themeDialog.close());themeDialog.addEventListener('click',event=>{if(event.target===themeDialog)themeDialog.close()});themeCards.forEach(card=>card.addEventListener('click',()=>{setTheme(card.dataset.themeChoice);setTimeout(()=>themeDialog.close(),560)}));

const MBOA_COPY={fr:{},kamfranglais:{}};const mboaLanguageButtons=[...document.querySelectorAll('[data-mboa-lang]')],mboaLanguageNotice=document.querySelector('.mboa-language-notice');function applyMboaLanguage(language){const safeLanguage=language==='kamfranglais'?'kamfranglais':'fr';document.documentElement.dataset.mboaLanguage=safeLanguage;localStorage.setItem('dunder-mboa-language',safeLanguage);mboaLanguageButtons.forEach(button=>{const active=button.dataset.mboaLang===safeLanguage;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});if(safeLanguage==='kamfranglais'){mboaLanguageNotice.classList.add('visible');clearTimeout(applyMboaLanguage.noticeTimer);applyMboaLanguage.noticeTimer=setTimeout(()=>mboaLanguageNotice.classList.remove('visible'),4200)}document.querySelectorAll('[data-i18n]').forEach(element=>{const key=element.dataset.i18n,copy=MBOA_COPY[safeLanguage][key];if(copy)element.textContent=copy})}mboaLanguageButtons.forEach(button=>button.addEventListener('click',()=>applyMboaLanguage(button.dataset.mboaLang)));applyMboaLanguage(localStorage.getItem('dunder-mboa-language')||'fr');
const menuButton=document.querySelector('.menu-toggle'),mobileMenu=document.querySelector('.mobile-menu');
menuButton.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});
mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('open');menuButton.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -6%'});
document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const topbar=document.querySelector('.topbar');let ticking=false;addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(()=>{topbar.classList.toggle('compact',scrollY>40);ticking=false});ticking=true}},{passive:true});
const artistCatalog=document.querySelector('#artist-catalog');
function artistCardMarkup(a,i,label){return `<article class="artist-card tone-${i%3+1} ${a.image?'has-artist-photo':''} ${focusIds.includes(a.id)?'editorial-focus':''}" style="${a.image?`--artist-image:url('${a.image}');--artist-focal:${a.focal};--artist-focal-mobile:${a.focalMobile}`:''}" tabindex="0" role="button" data-artist="${a.id}" aria-label="Voir le profil de ${esc(a.name)}"><span>${esc(label)}</span><div><h3>${esc(a.name)}</h3>${a.description?`<p class="artist-description">${esc(a.description)}</p>`:''}<button>Explorer →</button></div></article>`}
function renderArtists(){const favorite=shuffle(ARTISTS.filter(a=>focusIds.includes(a.id)))[0],rotation=shuffle(ARTISTS.filter(a=>!focusIds.includes(a.id))).slice(0,3),selection=shuffle([favorite,...rotation]);artistCatalog.innerHTML=selection.map((a,i)=>artistCardMarkup(a,i,focusIds.includes(a.id)?'FAVORI D-UNDER':(artistCategories(a)[0]||'FOCUS'))).join('')}
renderArtists();
const discoveryCatalog=document.querySelector('#discovery-catalog');function renderDiscovery(){const selection=shuffle(ARTISTS).slice(0,8);discoveryCatalog.innerHTML=selection.map((a,i)=>artistCardMarkup(a,i,artistCategories(a)[0]||'DÉCOUVERTE')).join('')}renderDiscovery();
const featuredReleases=document.querySelector('#featured-releases');
function renderFeatured(){featuredReleases.innerHTML=editorialOrder(FEATURED_RELEASES).slice(0,6).map(r=>`<article class="release-card ${focusIds.includes(r.artistId)?'editorial-focus':''}"><img src="${r.cover}" alt="Cover officielle de ${esc(r.title)}"><div><span>${focusIds.includes(r.artistId)?'FOCUS D-UNDER':esc(r.type)}</span><h3>${esc(r.title)}</h3><p>${esc(r.artist)}</p><button class="listen-trigger" data-listen="${esc(r.artistId+'|'+r.title)}">Écouter</button></div></article>`).join('')}
renderFeatured();
const musicCatalog=document.querySelector('#music-catalog');
function renderTracks(){musicCatalog.innerHTML=editorialOrder(FEATURED_RELEASES).map(r=>`<article class="${focusIds.includes(r.artistId)?'editorial-focus':''}"><span>✦</span><div class="cover" style="background-image:url('${r.cover}')"></div><div><h3>${esc(r.title)}</h3><p>${esc(r.artist)} · ${esc(r.date)}</p></div><span class="tag">${esc(r.type)}</span><button class="play-link listen-trigger" data-listen="${esc(r.artistId+'|'+r.title)}" aria-label="Écouter ${esc(r.title)}">↗</button></article>`).join('')}
renderTracks();
const artistRefresh=document.createElement('button');artistRefresh.className='shuffle-button';artistRefresh.textContent='Nouveau Focus ↻';artistCatalog.before(artistRefresh);artistRefresh.addEventListener('click',renderArtists);const discoveryRefresh=document.createElement('button');discoveryRefresh.className='shuffle-button';discoveryRefresh.textContent='Nouvelles découvertes ↻';discoveryCatalog.before(discoveryRefresh);discoveryRefresh.addEventListener('click',renderDiscovery);
const trackRefresh=document.createElement('button');trackRefresh.className='shuffle-button';trackRefresh.textContent='Changer la sélection ↻';musicCatalog.before(trackRefresh);trackRefresh.addEventListener('click',renderTracks);
const artistModal=document.querySelector('.artist-modal'),profile=document.querySelector('#artist-profile');
function openArtist(id){const a=ARTISTS.find(x=>x.id===id);if(!a)return;profile.innerHTML=`<div class="profile-hero ${a.image?'has-profile-photo':''}" style="${a.image?`--profile-image:url('${a.image}')`:''}"><p>${focusIds.includes(a.id)?'FOCUS D-UNDER':esc(a.status)}</p><h2>${esc(a.name)}</h2></div>${a.description?`<p class="profile-bio">${esc(a.description)}</p>`:''}<section><p class="section-kicker">Dernière sortie vérifiée</p>${a.releases[0]?`<div class="latest-release">${a.releases[0].cover?`<img src="${a.releases[0].cover}" alt="Cover de ${esc(a.releases[0].title)}">`:''}<div><h3>${esc(a.releases[0].title)}</h3><p>${esc(a.releases[0].type)} · ${esc(a.releases[0].date)}</p></div></div>`:'<p>Informations en cours de vérification.</p>'}</section><section><p class="section-kicker">Discographie vérifiée</p><div class="discography">${a.releases.map(r=>`<article>${r.cover?`<img class="release-cover" src="${r.cover}" alt="Cover de ${esc(r.title)}">`:''}<div><strong>${esc(r.title)}</strong><span>${esc(r.type)} · ${esc(r.date)}</span></div><ul>${r.tracks.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></article>`).join('')||'<p>En cours de vérification.</p>'}</div></section><button class="official-link listen-trigger" data-artist-listen="${a.id}">Écouter l'artiste</button>`;artistModal.showModal()}
artistCatalog.addEventListener('click',e=>{const card=e.target.closest('[data-artist]');if(card)openArtist(card.dataset.artist)});artistCatalog.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-artist]')){e.preventDefault();openArtist(e.target.dataset.artist)}});document.querySelector('.artist-close').addEventListener('click',()=>artistModal.close());
discoveryCatalog.addEventListener('click',e=>{const card=e.target.closest('[data-artist]');if(card)openArtist(card.dataset.artist)});discoveryCatalog.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-artist]')){e.preventDefault();openArtist(e.target.dataset.artist)}});
const modal=document.querySelector('.search-modal'),searchInput=document.querySelector('#global-search'),searchResults=document.querySelector('#search-results');document.querySelector('.search-open').addEventListener('click',()=>{modal.showModal();setTimeout(()=>searchInput.focus(),100)});document.querySelector('.search-close').addEventListener('click',()=>modal.close());
const normalizeSearch=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const SEARCH_INDEX=ARTISTS.map(artist=>({artist,searchable:normalizeSearch([artist.name,...(artist.aliases||[]),...(artist.categories||[]),...(artist.genres||[]),...artist.releases.flatMap(release=>[release.title,...release.tracks])].join(' ')),music:artist.releases.flatMap(release=>release.tracks.map(title=>({title,release:release.title,type:release.type,date:release.date,cover:release.cover||'',artist:artist.name,artistId:artist.id,searchable:normalizeSearch([title,release.title,artist.name,...(artist.aliases||[])].join(' '))}))) }));
function renderSearch(){const q=normalizeSearch(searchInput.value.trim());if(!q){searchResults.innerHTML='<p>Commence à saisir pour explorer la culture.</p>';return}const artistHits=SEARCH_INDEX.filter(entry=>entry.searchable.includes(q)).slice(0,8);const musicHits=SEARCH_INDEX.flatMap(entry=>entry.music).filter(item=>item.searchable.includes(q)).slice(0,12);searchResults.innerHTML=`<p class="search-count">${artistHits.length} artiste${artistHits.length!==1?'s':''} · ${musicHits.length} morceau${musicHits.length!==1?'x':''} / projet${musicHits.length!==1?'s':''}</p><div class="search-grid-premium"><section class="search-group"><h3>Artistes</h3>${artistHits.map(({artist})=>`<button class="search-artist-result" data-result-artist="${artist.id}"><span class="search-avatar" ${artist.image?`style="background-image:url('${artist.image}')"`:''}>${artist.image?'':esc(artist.name.split(/\s+/).map(word=>word[0]).slice(0,2).join(''))}</span><span><strong>${esc(artist.name)}</strong><span>${esc((artist.categories||[artist.status]).join(' · '))}</span></span></button>`).join('')||'<p class="search-empty">Aucun artiste vérifié</p>'}</section><section class="search-group"><h3>Morceaux & projets</h3>${musicHits.map(item=>`<article class="search-music-result"><span class="mini-cover" ${item.cover?`style="background-image:url('${item.cover}')"`:''}></span><div><strong>${esc(item.title)}</strong><span>${esc(item.artist)} · ${esc(item.release)} · ${esc(item.date)}</span></div></article>`).join('')||'<p class="search-empty">Aucun morceau ou projet vérifié</p>'}</section></div>`}
searchInput.addEventListener('input',renderSearch);searchResults.addEventListener('click',e=>{const b=e.target.closest('[data-result-artist]');if(b){modal.close();openArtist(b.dataset.resultArtist)}});

const sceneFilters=document.querySelector('#scene-filters'),sceneGrid=document.querySelector('#scene-grid'),scenePrev=document.querySelector('#scene-prev'),sceneNext=document.querySelector('#scene-next'),scenePageStatus=document.querySelector('#scene-page-status');const SCENE_CATEGORIES=[['all','Toute la scène'],['new-wave','New Wave'],['underground','Underground'],['rising','Rising'],['established','Established'],['legacy','Legacy']];
function artistCategories(artist){if(artist.categories?.length)return artist.categories;if(focusIds.includes(artist.id)||['dustry','mods','pef-jones'].includes(artist.id))return['new-wave','rising'];return['underground']}
const sceneCardMarkup=artist=>`<article class="scene-artist ${artist.image?'has-scene-photo':''}" style="${artist.image?`--scene-focal:${artist.focal||'50% 38%'};--scene-focal-mobile:${artist.focalMobile||artist.focal||'50% 35%'}`:''}" ${artist.image?`data-scene-image="${esc(artist.image)}"`:''} data-scene-artist="${artist.id}" tabindex="0" role="button" aria-label="Explorer ${esc(artist.name)}">${artist.image?'':`<span class="artist-monogram">${esc(artist.name.split(/\s+/).map(word=>word[0]).slice(0,2).join(''))}</span>`}<div><small>${esc(artistCategories(artist).join(' · '))}</small><h3>${esc(artist.name)}</h3><p>${esc((artist.genres||['Rap camerounais']).join(' · '))}</p><b>Explorer →</b></div></article>`;
function loadScenePage(index){[index-1,index,index+1].forEach(i=>{const page=sceneGrid.children[i];if(!page||page.dataset.imagesLoaded)return;page.querySelectorAll('[data-scene-image]').forEach(card=>card.style.setProperty('--scene-image',`url("${card.dataset.sceneImage.replace(/"/g,'&quot;')}")`));page.dataset.imagesLoaded='true'})}
function scenePageSize(){return innerWidth<=560?2:innerWidth<=920?4:8}function updateSceneNav(){const pageWidth=sceneGrid.clientWidth,current=Math.round(sceneGrid.scrollLeft/Math.max(pageWidth,1)),total=sceneGrid.children.length;loadScenePage(current);scenePrev.disabled=current<=0;sceneNext.disabled=current>=total-1;scenePageStatus.textContent=total?`${Math.min(current+1,total)} / ${total}`:'0 / 0'}
function renderScene(category='all'){sceneFilters.innerHTML=SCENE_CATEGORIES.map(([value,label])=>`<button data-scene-filter="${value}" class="${value===category?'active':''}" aria-pressed="${value===category}">${label}</button>`).join('');const artists=shuffle(ARTISTS.filter(artist=>category==='all'||artistCategories(artist).includes(category))),pageSize=scenePageSize(),pages=[];for(let i=0;i<artists.length;i+=pageSize)pages.push(artists.slice(i,i+pageSize));sceneGrid.innerHTML=pages.map((page,index)=>`<div class="scene-page" aria-label="Page ${index+1} sur ${pages.length}">${page.map(sceneCardMarkup).join('')}</div>`).join('');sceneGrid.scrollLeft=0;requestAnimationFrame(updateSceneNav)}
sceneFilters.addEventListener('click',event=>{const button=event.target.closest('[data-scene-filter]');if(button)renderScene(button.dataset.sceneFilter)});sceneGrid.addEventListener('click',event=>{const card=event.target.closest('[data-scene-artist]');if(card)openArtist(card.dataset.sceneArtist)});sceneGrid.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-scene-artist]')){event.preventDefault();openArtist(event.target.dataset.sceneArtist)}});renderScene();
scenePrev.addEventListener('click',()=>sceneGrid.scrollBy({left:-sceneGrid.clientWidth,behavior:'smooth'}));sceneNext.addEventListener('click',()=>sceneGrid.scrollBy({left:sceneGrid.clientWidth,behavior:'smooth'}));let sceneScrollTick=false;sceneGrid.addEventListener('scroll',()=>{if(!sceneScrollTick){requestAnimationFrame(()=>{updateSceneNav();sceneScrollTick=false});sceneScrollTick=true}},{passive:true});let sceneResizeTimer;addEventListener('resize',()=>{clearTimeout(sceneResizeTimer);sceneResizeTimer=setTimeout(()=>{const active=sceneFilters.querySelector('.active');renderScene(active?.dataset.sceneFilter||'all')},180)});
document.querySelector('.community form').addEventListener('submit',event=>{event.preventDefault();event.currentTarget.querySelector('button').textContent='Bienvenue ✓';event.currentTarget.querySelector('input').value=''});

const listenDialog=document.querySelector('.listen-dialog'),listenTitle=document.querySelector('#listen-title'),listenArtist=document.querySelector('#listen-artist'),listenServices=document.querySelector('#listen-services');
const serviceNames={spotify:'Spotify',apple:'Apple Music'};
function openListen(key){const [artistId,...titleParts]=key.split('|'),title=titleParts.join('|');const release=FEATURED_RELEASES.find(r=>r.artistId===artistId&&r.title===title);if(!release)return;listenTitle.textContent=release.title;listenArtist.textContent=release.artist;listenServices.className='listen-services';listenServices.innerHTML=['spotify','apple'].map(service=>release.links?.[service]?`<a class="service-link" href="${release.links[service]}" target="_blank" rel="noopener"><span class="service-icon ${service}-icon">${service==='spotify'?'●':'♪'}</span>${serviceNames[service]} <span aria-hidden="true">↗</span></a>`:`<div class="service-missing" aria-disabled="true"><span class="service-icon ${service}-icon">${service==='spotify'?'●':'♪'}</span>${serviceNames[service]}<small>LIEN EXACT À CONFIRMER</small></div>`).join('');listenDialog.showModal()}
function openArtistListen(id){const artist=ARTISTS.find(a=>a.id===id);if(!artist)return;const links={};if(artist.source?.includes('open.spotify.com/artist/'))links.spotify=artist.source;if(artist.source?.includes('music.apple.com/')&&artist.source.includes('/artist/'))links.apple=artist.source;listenTitle.textContent=artist.name;listenArtist.textContent='Profil artiste officiel';listenServices.className='listen-services';listenServices.innerHTML=['spotify','apple'].map(service=>links[service]?`<a class="service-link" href="${links[service]}" target="_blank" rel="noopener"><span class="service-icon ${service}-icon">${service==='spotify'?'●':'♪'}</span>${serviceNames[service]} <span aria-hidden="true">↗</span></a>`:`<div class="service-missing" aria-disabled="true"><span class="service-icon ${service}-icon">${service==='spotify'?'●':'♪'}</span>${serviceNames[service]}<small>PROFIL EXACT À CONFIRMER</small></div>`).join('');artistModal.close();listenDialog.showModal()}
document.addEventListener('click',event=>{const trigger=event.target.closest('[data-listen]');if(trigger)openListen(trigger.dataset.listen);const artistTrigger=event.target.closest('[data-artist-listen]');if(artistTrigger)openArtistListen(artistTrigger.dataset.artistListen)});document.querySelector('.listen-close').addEventListener('click',()=>listenDialog.close());listenDialog.addEventListener('click',event=>{if(event.target===listenDialog)listenDialog.close()});

const preferenceButtons=[...document.querySelectorAll('[data-preference]')];
function setPreference(value){localStorage.setItem('dunder-music-preference',value);preferenceButtons.forEach(button=>{const active=button.dataset.preference===value;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))})}
preferenceButtons.forEach(button=>button.addEventListener('click',()=>setPreference(button.dataset.preference)));setPreference(localStorage.getItem('dunder-music-preference')||'spotify');

const chartPanel=document.querySelector('#chart-panel'),chartTabs=[...document.querySelectorAll('[data-chart-tab]')];
function renderChart(type){const label=type==='artists'?'artistes':'titres';chartPanel.innerHTML=`<div class="chart-empty"><span class="chart-status"><i></i>Données en attente de connexion officielle</span><div class="chart-number">#—</div><h3>Top ${label} bientôt disponible.</h3><p>D-UNDER prépare cette édition sans fabriquer de streams, d'auditeurs ou de mouvements. Le classement apparaîtra dès qu'un jeu de données comparable et légitimement accessible couvrira suffisamment d'artistes.</p></div>`;chartTabs.forEach(tab=>{const active=tab.dataset.chartTab===type;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active))})}
chartTabs.forEach(tab=>tab.addEventListener('click',()=>renderChart(tab.dataset.chartTab)));renderChart('artists');

const picks=document.querySelector('#editorial-picks');picks.innerHTML=FEATURED_RELEASES.filter(r=>focusIds.includes(r.artistId)).slice(0,3).map((r,i)=>`<article class="pick-card" style="background-image:url('${r.cover}')"><small>0${i+1} · SÉLECTION ÉDITORIALE</small><h3>${esc(r.artist)}</h3><p>${esc(r.title)}</p></article>`).join('');
